// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fixqfyyrryfzdszeydbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpeHFmeXlycnlmemRzemV5ZGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzAyMjQsImV4cCI6MjA2MDkwNjIyNH0.i-vh0jTHGvu2GE93xRtvAttN1oYvsE32EpLEZplAPV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);